//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.1008
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SampleCards {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SampleCards() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.SampleCards", typeof(SampleCards).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] Outlook2007 {
            get {
                object obj = ResourceManager.GetObject("Outlook2007", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] OutlookCertificate {
            get {
                object obj = ResourceManager.GetObject("OutlookCertificate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] OutlookSimple {
            get {
                object obj = ResourceManager.GetObject("OutlookSimple", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PalmAgentSamples {
            get {
                object obj = ResourceManager.GetObject("PalmAgentSamples", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RfcAuthors {
            get {
                object obj = ResourceManager.GetObject("RfcAuthors", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] XPalmWithPhoto {
            get {
                object obj = ResourceManager.GetObject("XPalmWithPhoto", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
