//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace SmsTest.net.webservicex.www {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SendSMSSoap", Namespace="http://www.webserviceX.NET")]
    public class SendSMS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public SendSMS() {
            this.Url = "http://www.webservicex.net/SendSMS.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webserviceX.NET/SendSMSToIndia", RequestNamespace="http://www.webserviceX.NET", ResponseNamespace="http://www.webserviceX.NET", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SMSResult SendSMSToIndia(string MobileNumber, string FromEmailAddress, string Message) {
            object[] results = this.Invoke("SendSMSToIndia", new object[] {
                        MobileNumber,
                        FromEmailAddress,
                        Message});
            return ((SMSResult)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSendSMSToIndia(string MobileNumber, string FromEmailAddress, string Message, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SendSMSToIndia", new object[] {
                        MobileNumber,
                        FromEmailAddress,
                        Message}, callback, asyncState);
        }
        
        /// <remarks/>
        public SMSResult EndSendSMSToIndia(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SMSResult)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.webserviceX.NET")]
    public class SMSResult {
        
        /// <remarks/>
        public string FromEmailAddress;
        
        /// <remarks/>
        public string MobileNumber;
        
        /// <remarks/>
        public string Provider;
        
        /// <remarks/>
        public string State;
        
        /// <remarks/>
        public string Status;
    }
}
