'===============================================================================
' OSML - Open Source Messaging Library
'
'===============================================================================
' Copyright © TWIT88.COM.  All rights reserved.
'
' This file is part of Open Source Messaging Library.
'
' Open Source Messaging Library is free software: you can redistribute it
' and/or modify it under the terms of the GNU General Public License version 3.
'
' Open Source Messaging Library is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this software.  If not, see <http://www.gnu.org/licenses/>.
'===============================================================================

Imports System.Collections.Generic
Imports System.Text
Imports System.Collections
Imports System.Windows.Forms

'Namespace MessagingToolkit.Core.Utilities
''' <summary>
''' Message content
''' </summary>
Public Class MessageContent

    ''' <summary>
    ''' Initializes a new instance of the <see cref="MessageContent"/> class.
    ''' </summary>
    ''' <param name="contentType">Type of the content.</param>
    ''' <param name="contentId">The content id.</param>
    ''' <param name="fileName">Name of the file.</param>
    Public Sub New(ByVal contentType As String, ByVal contentId As String, ByVal fileName As String)
        Me.ContentType = contentType
        Me.ContentId = contentId
        Me.FileName = fileName
    End Sub

    ''' <summary>
    ''' Gets or sets the type of the content.
    ''' </summary>
    ''' <value>The type of the content.</value>
    Public Property ContentType() As String
        Get
            Return m_ContentType
        End Get
        Private Set(ByVal value As String)
            m_ContentType = value
        End Set
    End Property
    Private m_ContentType As String

    ''' <summary>
    ''' Gets or sets the content id.
    ''' </summary>
    ''' <value>The content id.</value>
    Public Property ContentId() As String
        Get
            Return m_ContentId
        End Get
        Private Set(ByVal value As String)
            m_ContentId = value
        End Set
    End Property
    Private m_ContentId As String

    ''' <summary>
    ''' File name
    ''' </summary>
    ''' <value>The name of the file.</value>
    Public Property FileName() As String
        Get
            Return m_FileName
        End Get
        Private Set(ByVal value As String)
            m_FileName = value
        End Set
    End Property
    Private m_FileName As String
End Class

'End Namespace


Public NotInheritable Class MIMETypes
 
    Public Shared Function ContentType(ByVal strExtension As String) As String
        If MIMETypeList.ContainsKey(strExtension) Then
            Return MIMETypeList(strExtension).ToString()
        End If

        Return Nothing
    End Function

    Public Shared Property MIMETypeList() As Hashtable
        Get
            Return m_MIMETypeList
        End Get
        Set(ByVal value As Hashtable)
            m_MIMETypeList = value
        End Set
    End Property
    Public Shared m_MIMETypeList As Hashtable

    Shared Sub New()
        Try
            MIMETypeList = New Hashtable()
            'MIMETypeList.Add(".323", "text/h323");
            'MIMETypeList.Add(".3gp", "video/3gpp");
            'MIMETypeList.Add(".3gpp", "video/3gpp");
            'MIMETypeList.Add(".acp", "audio/x-mei-aac");
            'MIMETypeList.Add(".act", "text/xml");
            'MIMETypeList.Add(".actproj", "text/plain");
            'MIMETypeList.Add(".ade", "application/msaccess");
            'MIMETypeList.Add(".adp", "application/msaccess");
            'MIMETypeList.Add(".ai", "application/postscript");
            'MIMETypeList.Add(".aif", "audio/aiff");
            'MIMETypeList.Add(".aifc", "audio/aiff");
            'MIMETypeList.Add(".aiff", "audio/aiff");
            'MIMETypeList.Add(".asf", "video/x-ms-asf");
            'MIMETypeList.Add(".asm", "text/plain");
            'MIMETypeList.Add(".asx", "video/x-ms-asf");
            'MIMETypeList.Add(".au", "audio/basic");
            'MIMETypeList.Add(".avi", "video/avi");
            'MIMETypeList.Add(".bmp", "image/bmp");
            'MIMETypeList.Add(".bwp", "application/x-bwpreview");
            'MIMETypeList.Add(".c", "text/plain");
            'MIMETypeList.Add(".cat", "application/vnd.ms-pki.seccat");
            'MIMETypeList.Add(".cc", "text/plain");
            'MIMETypeList.Add(".cdf", "application/x-cdf");
            'MIMETypeList.Add(".cer", "application/x-x509-ca-cert");
            'MIMETypeList.Add(".cod", "text/plain");
            'MIMETypeList.Add(".cpp", "text/plain");
            'MIMETypeList.Add(".crl", "application/pkix-crl");
            'MIMETypeList.Add(".crt", "application/x-x509-ca-cert");
            'MIMETypeList.Add(".cs", "text/plain");
            'MIMETypeList.Add(".css", "text/css");
            'MIMETypeList.Add(".csv", "application/vnd.ms-excel");
            'MIMETypeList.Add(".cxx", "text/plain");
            'MIMETypeList.Add(".dbs", "text/plain");
            'MIMETypeList.Add(".def", "text/plain");
            'MIMETypeList.Add(".der", "application/x-x509-ca-cert");
            'MIMETypeList.Add(".dib", "image/bmp");
            'MIMETypeList.Add(".dif", "video/x-dv");
            'MIMETypeList.Add(".dll", "application/x-msdownload");
            'MIMETypeList.Add(".doc", "application/msword");
            'MIMETypeList.Add(".dot", "application/msword");
            'MIMETypeList.Add(".dsp", "text/plain");
            'MIMETypeList.Add(".dsw", "text/plain");
            'MIMETypeList.Add(".dv", "video/x-dv");
            'MIMETypeList.Add(".edn", "application/vnd.adobe.edn");
            'MIMETypeList.Add(".eml", "message/rfc822");
            'MIMETypeList.Add(".eps", "application/postscript");
            'MIMETypeList.Add(".etd", "application/x-ebx");
            'MIMETypeList.Add(".etp", "text/plain");
            'MIMETypeList.Add(".exe", "application/x-msdownload");
            'MIMETypeList.Add(".ext", "text/plain");
            'MIMETypeList.Add(".fdf", "application/vnd.fdf");
            'MIMETypeList.Add(".fif", "application/fractals");
            'MIMETypeList.Add(".fky", "text/plain");
            'MIMETypeList.Add(".gif", "image/gif");
            'MIMETypeList.Add(".gz", "application/x-gzip");
            'MIMETypeList.Add(".h", "text/plain");
            'MIMETypeList.Add(".hpp", "text/plain");
            'MIMETypeList.Add(".hqx", "application/mac-binhex40");
            'MIMETypeList.Add(".hta", "application/hta");
            'MIMETypeList.Add(".htc", "text/x-component");
            'MIMETypeList.Add(".htm", "text/html");
            'MIMETypeList.Add(".html", "text/html");
            'MIMETypeList.Add(".htt", "text/webviewhtml");
            'MIMETypeList.Add(".hxx", "text/plain");
            'MIMETypeList.Add(".i", "text/plain");
            'MIMETypeList.Add(".iad", "application/x-iad");
            'MIMETypeList.Add(".ico", "image/x-icon");
            'MIMETypeList.Add(".ics", "text/calendar");
            'MIMETypeList.Add(".idl", "text/plain");
            'MIMETypeList.Add(".iii", "application/x-iphone");
            'MIMETypeList.Add(".inc", "text/plain");
            'MIMETypeList.Add(".infopathxml", "application/ms-infopath.xml");
            'MIMETypeList.Add(".inl", "text/plain");
            'MIMETypeList.Add(".ins", "application/x-internet-signup");
            'MIMETypeList.Add(".iqy", "text/x-ms-iqy");
            'MIMETypeList.Add(".isp", "application/x-internet-signup");
            'MIMETypeList.Add(".java", "text/java");
            'MIMETypeList.Add(".jfif", "image/jpeg");
            'MIMETypeList.Add(".jnlp", "application/x-java-jnlp-file");
            'MIMETypeList.Add(".jpe", "image/jpeg");
            'MIMETypeList.Add(".jpeg", "image/jpeg");
            'MIMETypeList.Add(".jpg", "image/jpeg");
            'MIMETypeList.Add(".jsl", "text/plain");
            'MIMETypeList.Add(".kci", "text/plain");
            'MIMETypeList.Add(".la1", "audio/x-liquid-file");
            'MIMETypeList.Add(".lar", "application/x-laplayer-reg");
            'MIMETypeList.Add(".latex", "application/x-latex");
            'MIMETypeList.Add(".lavs", "audio/x-liquid-secure");
            'MIMETypeList.Add(".lgn", "text/plain");
            'MIMETypeList.Add(".lmsff", "audio/x-la-lms");
            'MIMETypeList.Add(".lqt", "audio/x-la-lqt");
            'MIMETypeList.Add(".lst", "text/plain");
            'MIMETypeList.Add(".m1v", "video/mpeg");
            'MIMETypeList.Add(".m3u", "audio/mpegurl");
            'MIMETypeList.Add(".m4e", "video/mpeg4");
            'MIMETypeList.Add(".MAC", "image/x-macpaint");
            'MIMETypeList.Add(".mak", "text/plain");
            'MIMETypeList.Add(".man", "application/x-troff-man");
            'MIMETypeList.Add(".map", "text/plain");
            'MIMETypeList.Add(".mda", "application/msaccess");
            'MIMETypeList.Add(".mdb", "application/msaccess");
            'MIMETypeList.Add(".mde", "application/msaccess");
            'MIMETypeList.Add(".mdi", "image/vnd.ms-modi");
            'MIMETypeList.Add(".mfp", "application/x-shockwave-flash");
            'MIMETypeList.Add(".mht", "message/rfc822");
            'MIMETypeList.Add(".mhtml", "message/rfc822");
            'MIMETypeList.Add(".mid", "audio/mid");
            'MIMETypeList.Add(".midi", "audio/mid");
            'MIMETypeList.Add(".mk", "text/plain");
            'MIMETypeList.Add(".mnd", "audio/x-musicnet-download");
            'MIMETypeList.Add(".mns", "audio/x-musicnet-stream");
            'MIMETypeList.Add(".MP1", "audio/mp1");
            'MIMETypeList.Add(".mp2", "video/mpeg");
            'MIMETypeList.Add(".mp2v", "video/mpeg");
            'MIMETypeList.Add(".mp3", "audio/mpeg");
            'MIMETypeList.Add(".mp4", "video/mp4");
            'MIMETypeList.Add(".mpa", "video/mpeg");
            'MIMETypeList.Add(".mpe", "video/mpeg");
            'MIMETypeList.Add(".mpeg", "video/mpeg");
            'MIMETypeList.Add(".mpf", "application/vnd.ms-mediapackage");
            'MIMETypeList.Add(".mpg", "video/mpeg");
            'MIMETypeList.Add(".mpg4", "video/mp4");
            'MIMETypeList.Add(".mpga", "audio/rn-mpeg");
            'MIMETypeList.Add(".mpv2", "video/mpeg");
            'MIMETypeList.Add(".NMW", "application/nmwb");
            'MIMETypeList.Add(".nws", "message/rfc822");
            'MIMETypeList.Add(".odc", "text/x-ms-odc");
            'MIMETypeList.Add(".odh", "text/plain");
            'MIMETypeList.Add(".odl", "text/plain");
            'MIMETypeList.Add(".p10", "application/pkcs10");
            'MIMETypeList.Add(".p12", "application/x-pkcs12");
            'MIMETypeList.Add(".p7b", "application/x-pkcs7-certificates");
            'MIMETypeList.Add(".p7c", "application/pkcs7-mime");
            'MIMETypeList.Add(".p7m", "application/pkcs7-mime");
            'MIMETypeList.Add(".p7r", "application/x-pkcs7-certreqresp");
            'MIMETypeList.Add(".p7s", "application/pkcs7-signature");
            'MIMETypeList.Add(".PCT", "image/pict");
            'MIMETypeList.Add(".pdf", "application/pdf");
            'MIMETypeList.Add(".pdx", "application/vnd.adobe.pdx");
            'MIMETypeList.Add(".pfx", "application/x-pkcs12");
            'MIMETypeList.Add(".pic", "image/pict");
            'MIMETypeList.Add(".PICT", "image/pict");
            'MIMETypeList.Add(".pko", "application/vnd.ms-pki.pko");
            'MIMETypeList.Add(".png", "image/png");
            'MIMETypeList.Add(".pnt", "image/x-macpaint");
            'MIMETypeList.Add(".pntg", "image/x-macpaint");
            'MIMETypeList.Add(".pot", "application/vnd.ms-powerpoint");
            'MIMETypeList.Add(".ppa", "application/vnd.ms-powerpoint");
            'MIMETypeList.Add(".pps", "application/vnd.ms-powerpoint");
            'MIMETypeList.Add(".ppt", "application/vnd.ms-powerpoint");
            'MIMETypeList.Add(".prc", "text/plain");
            'MIMETypeList.Add(".prf", "application/pics-rules");
            'MIMETypeList.Add(".ps", "application/postscript");
            'MIMETypeList.Add(".pub", "application/vnd.ms-publisher");
            'MIMETypeList.Add(".pwz", "application/vnd.ms-powerpoint");
            'MIMETypeList.Add(".qt", "video/quicktime");
            'MIMETypeList.Add(".qti", "image/x-quicktime");
            'MIMETypeList.Add(".qtif", "image/x-quicktime");
            'MIMETypeList.Add(".qtl", "application/x-quicktimeplayer");
            'MIMETypeList.Add(".qup", "application/x-quicktimeupdater");
            'MIMETypeList.Add(".r1m", "application/vnd.rn-recording");
            'MIMETypeList.Add(".r3t", "text/vnd.rn-realtext3d");
            'MIMETypeList.Add(".RA", "audio/vnd.rn-realaudio");
            'MIMETypeList.Add(".rar", "application/x-rar-compressed");
            'MIMETypeList.Add(".RAM", "audio/x-pn-realaudio");
            'MIMETypeList.Add(".rat", "application/rat-file");
            'MIMETypeList.Add(".rc", "text/plain");
            'MIMETypeList.Add(".rc2", "text/plain");
            'MIMETypeList.Add(".rct", "text/plain");
            'MIMETypeList.Add(".rec", "application/vnd.rn-recording");
            'MIMETypeList.Add(".rgs", "text/plain");
            'MIMETypeList.Add(".rjs", "application/vnd.rn-realsystem-rjs");
            'MIMETypeList.Add(".rjt", "application/vnd.rn-realsystem-rjt");
            'MIMETypeList.Add(".RM", "application/vnd.rn-realmedia");
            'MIMETypeList.Add(".rmf", "application/vnd.adobe.rmf");
            'MIMETypeList.Add(".rmi", "audio/mid");
            'MIMETypeList.Add(".RMJ", "application/vnd.rn-realsystem-rmj");
            'MIMETypeList.Add(".RMM", "audio/x-pn-realaudio");
            'MIMETypeList.Add(".rms", "application/vnd.rn-realmedia-secure");
            'MIMETypeList.Add(".rmvb", "application/vnd.rn-realmedia-vbr");
            'MIMETypeList.Add(".RMX", "application/vnd.rn-realsystem-rmx");
            'MIMETypeList.Add(".RNX", "application/vnd.rn-realplayer");
            'MIMETypeList.Add(".rp", "image/vnd.rn-realpix");
            'MIMETypeList.Add(".RPM", "audio/x-pn-realaudio-plugin");
            'MIMETypeList.Add(".rqy", "text/x-ms-rqy");
            'MIMETypeList.Add(".rsml", "application/vnd.rn-rsml");
            'MIMETypeList.Add(".rt", "text/vnd.rn-realtext");
            'MIMETypeList.Add(".rtf", "application/msword");
            'MIMETypeList.Add(".rul", "text/plain");
            'MIMETypeList.Add(".RV", "video/vnd.rn-realvideo");
            'MIMETypeList.Add(".s", "text/plain");
            'MIMETypeList.Add(".sc2", "application/schdpl32");
            'MIMETypeList.Add(".scd", "application/schdpl32");
            'MIMETypeList.Add(".sch", "application/schdpl32");
            'MIMETypeList.Add(".sct", "text/scriptlet");
            'MIMETypeList.Add(".sd2", "audio/x-sd2");
            'MIMETypeList.Add(".sdp", "application/sdp");
            'MIMETypeList.Add(".sit", "application/x-stuffit");
            'MIMETypeList.Add(".slk", "application/vnd.ms-excel");
            'MIMETypeList.Add(".sln", "application/octet-stream");
            'MIMETypeList.Add(".SMI", "application/smil");
            'MIMETypeList.Add(".smil", "application/smil");
            'MIMETypeList.Add(".snd", "audio/basic");
            'MIMETypeList.Add(".snp", "application/msaccess");
            'MIMETypeList.Add(".spc", "application/x-pkcs7-certificates");
            'MIMETypeList.Add(".spl", "application/futuresplash");
            'MIMETypeList.Add(".sql", "text/plain");
            'MIMETypeList.Add(".srf", "text/plain");
            'MIMETypeList.Add(".ssm", "application/streamingmedia");
            'MIMETypeList.Add(".sst", "application/vnd.ms-pki.certstore");
            'MIMETypeList.Add(".stl", "application/vnd.ms-pki.stl");
            'MIMETypeList.Add(".swf", "application/x-shockwave-flash");
            'MIMETypeList.Add(".tab", "text/plain");
            'MIMETypeList.Add(".tar", "application/x-tar");
            'MIMETypeList.Add(".tdl", "text/xml");
            'MIMETypeList.Add(".tgz", "application/x-compressed");
            'MIMETypeList.Add(".tif", "image/tiff");
            'MIMETypeList.Add(".tiff", "image/tiff");
            'MIMETypeList.Add(".tlh", "text/plain");
            'MIMETypeList.Add(".tli", "text/plain");
            'MIMETypeList.Add(".torrent", "application/x-bittorrent");
            'MIMETypeList.Add(".trg", "text/plain");
            'MIMETypeList.Add(".txt", "text/plain");
            'MIMETypeList.Add(".udf", "text/plain");
            'MIMETypeList.Add(".udt", "text/plain");
            'MIMETypeList.Add(".uls", "text/iuls");
            'MIMETypeList.Add(".user", "text/plain");
            'MIMETypeList.Add(".usr", "text/plain");
            'MIMETypeList.Add(".vb", "text/plain");
            'MIMETypeList.Add(".vcf", "text/x-vcard");
            'MIMETypeList.Add(".vcproj", "text/plain");
            'MIMETypeList.Add(".viw", "text/plain");
            'MIMETypeList.Add(".vpg", "application/x-vpeg005");
            'MIMETypeList.Add(".vspscc", "text/plain");
            'MIMETypeList.Add(".vsscc", "text/plain");
            'MIMETypeList.Add(".vssscc", "text/plain");
            'MIMETypeList.Add(".wav", "audio/wav");
            'MIMETypeList.Add(".wax", "audio/x-ms-wax");
            'MIMETypeList.Add(".wbk", "application/msword");
            'MIMETypeList.Add(".wiz", "application/msword");
            'MIMETypeList.Add(".wm", "video/x-ms-wm");
            'MIMETypeList.Add(".wma", "audio/x-ms-wma");
            'MIMETypeList.Add(".wmd", "application/x-ms-wmd");
            'MIMETypeList.Add(".wmv", "video/x-ms-wmv");
            'MIMETypeList.Add(".wmx", "video/x-ms-wmx");
            'MIMETypeList.Add(".wmz", "application/x-ms-wmz");
            'MIMETypeList.Add(".wpl", "application/vnd.ms-wpl");
            'MIMETypeList.Add(".wprj", "application/webzip");
            'MIMETypeList.Add(".wsc", "text/scriptlet");
            'MIMETypeList.Add(".wvx", "video/x-ms-wvx");
            'MIMETypeList.Add(".XBM", "image/x-xbitmap");
            'MIMETypeList.Add(".xdp", "application/vnd.adobe.xdp+xml");
            'MIMETypeList.Add(".xfd", "application/vnd.adobe.xfd+xml");
            'MIMETypeList.Add(".xfdf", "application/vnd.adobe.xfdf");
            'MIMETypeList.Add(".xla", "application/vnd.ms-excel");
            'MIMETypeList.Add(".xlb", "application/vnd.ms-excel");
            'MIMETypeList.Add(".xlc", "application/vnd.ms-excel");
            'MIMETypeList.Add(".xld", "application/vnd.ms-excel");
            'MIMETypeList.Add(".xlk", "application/vnd.ms-excel");
            'MIMETypeList.Add(".xll", "application/vnd.ms-excel");
            'MIMETypeList.Add(".xlm", "application/vnd.ms-excel");
            'MIMETypeList.Add(".xls", "application/vnd.ms-excel");
            'MIMETypeList.Add(".xlt", "application/vnd.ms-excel");
            'MIMETypeList.Add(".xlv", "application/vnd.ms-excel");
            'MIMETypeList.Add(".xlw", "application/vnd.ms-excel");
            'MIMETypeList.Add(".xml", "text/xml");
            'MIMETypeList.Add(".xpl", "audio/scpls");
            'MIMETypeList.Add(".xsl", "text/xml");
            'MIMETypeList.Add(".z", "application/x-compress");
            'MIMETypeList.Add(".zip", "application/x-zip-compressed");
            MIMETypeList.Add(".3dm", "x-world/x-3dmf")
            MIMETypeList.Add(".3dmf", "x-world/x-3dmf")
            MIMETypeList.Add(".a", "application/octet-stream")
            MIMETypeList.Add(".aab", "application/x-authorware-bin")
            MIMETypeList.Add(".aam", "application/x-authorware-map")
            MIMETypeList.Add(".aas", "application/x-authorware-seg")
            MIMETypeList.Add(".abc", "text/vnd.abc")
            MIMETypeList.Add(".acgi", "text/html")
            MIMETypeList.Add(".afl", "video/animaflex")
            MIMETypeList.Add(".ai", "application/postscript")
            MIMETypeList.Add(".aif", "audio/aiff")
            'MIMETypeList.Add(".aif", "audio/x-aiff");
            MIMETypeList.Add(".aifc", "audio/aiff")
            'MIMETypeList.Add(".aifc", "audio/x-aiff");
            MIMETypeList.Add(".aiff", "audio/aiff")
            'MIMETypeList.Add(".aiff", "audio/x-aiff");
            MIMETypeList.Add(".aim", "application/x-aim")
            MIMETypeList.Add(".aip", "text/x-audiosoft-intra")
            MIMETypeList.Add(".ani", "application/x-navi-animation")
            MIMETypeList.Add(".aos", "application/x-nokia-9000-communicator-add-on-software")
            MIMETypeList.Add(".aps", "application/mime")
            MIMETypeList.Add(".arc", "application/octet-stream")
            MIMETypeList.Add(".arj", "application/arj")
            'MIMETypeList.Add(".arj", "application/octet-stream");
            MIMETypeList.Add(".art", "image/x-jg")
            MIMETypeList.Add(".asf", "video/x-ms-asf")
            MIMETypeList.Add(".asm", "text/x-asm")
            MIMETypeList.Add(".asp", "text/asp")
            'MIMETypeList.Add(".asx", "application/x-mplayer2");
            MIMETypeList.Add(".asx", "video/x-ms-asf")
            'MIMETypeList.Add(".asx", "video/x-ms-asf-plugin");
            MIMETypeList.Add(".au", "audio/basic")
            'MIMETypeList.Add(".au", "audio/x-au");
            'MIMETypeList.Add(".avi", "application/x-troff-msvideo");
            MIMETypeList.Add(".avi", "video/avi")
            'MIMETypeList.Add(".avi", "video/msvideo");
            'MIMETypeList.Add(".avi", "video/x-msvideo");
            MIMETypeList.Add(".avs", "video/avs-video")
            MIMETypeList.Add(".bcpio", "application/x-bcpio")
            'MIMETypeList.Add(".bin", "application/mac-binary");
            'MIMETypeList.Add(".bin", "application/macbinary");
            MIMETypeList.Add(".bin", "application/octet-stream")
            'MIMETypeList.Add(".bin", "application/x-binary");
            'MIMETypeList.Add(".bin", "application/x-macbinary");
            MIMETypeList.Add(".bm", "image/bmp")
            MIMETypeList.Add(".bmp", "image/bmp")
            'MIMETypeList.Add(".bmp", "image/x-windows-bmp");
            MIMETypeList.Add(".boo", "application/book")
            MIMETypeList.Add(".book", "application/book")
            MIMETypeList.Add(".boz", "application/x-bzip2")
            MIMETypeList.Add(".bsh", "application/x-bsh")
            MIMETypeList.Add(".bz", "application/x-bzip")
            MIMETypeList.Add(".bz2", "application/x-bzip2")
            MIMETypeList.Add(".c", "text/plain")
            'MIMETypeList.Add(".c", "text/x-c");
            MIMETypeList.Add(".c++", "text/plain")
            MIMETypeList.Add(".cat", "application/vnd.ms-pki.seccat")
            MIMETypeList.Add(".cc", "text/plain")
            'MIMETypeList.Add(".cc", "text/x-c");
            MIMETypeList.Add(".ccad", "application/clariscad")
            MIMETypeList.Add(".cco", "application/x-cocoa")
            MIMETypeList.Add(".cdf", "application/cdf")
            'MIMETypeList.Add(".cdf", "application/x-cdf");
            'MIMETypeList.Add(".cdf", "application/x-netcdf");
            MIMETypeList.Add(".cer", "application/pkix-cert")
            'MIMETypeList.Add(".cer", "application/x-x509-ca-cert");
            MIMETypeList.Add(".cha", "application/x-chat")
            MIMETypeList.Add(".chat", "application/x-chat")
            MIMETypeList.Add(".class", "application/java")
            'MIMETypeList.Add(".class", "application/java-byte-code");
            'MIMETypeList.Add(".class", "application/x-java-class");
            'MIMETypeList.Add(".com", "application/octet-stream");
            MIMETypeList.Add(".com", "text/plain")
            MIMETypeList.Add(".conf", "text/plain")
            MIMETypeList.Add(".cpio", "application/x-cpio")
            MIMETypeList.Add(".cpp", "text/x-c")
            'MIMETypeList.Add(".cpt", "application/mac-compactpro");
            'MIMETypeList.Add(".cpt", "application/x-compactpro");
            MIMETypeList.Add(".cpt", "application/x-cpt")
            MIMETypeList.Add(".crl", "application/pkcs-crl")
            'MIMETypeList.Add(".crl", "application/pkix-crl");
            MIMETypeList.Add(".crt", "application/pkix-cert")
            'MIMETypeList.Add(".crt", "application/x-x509-ca-cert");
            'MIMETypeList.Add(".crt", "application/x-x509-user-cert");
            MIMETypeList.Add(".csh", "application/x-csh")
            'MIMETypeList.Add(".csh", "text/x-script.csh");
            'MIMETypeList.Add(".css", "application/x-pointplus");
            MIMETypeList.Add(".css", "text/css")
            MIMETypeList.Add(".cxx", "text/plain")
            MIMETypeList.Add(".dcr", "application/x-director")
            MIMETypeList.Add(".deepv", "application/x-deepv")
            MIMETypeList.Add(".def", "text/plain")
            MIMETypeList.Add(".der", "application/x-x509-ca-cert")
            MIMETypeList.Add(".dif", "video/x-dv")
            MIMETypeList.Add(".dir", "application/x-director")
            MIMETypeList.Add(".dl", "video/dl")
            'MIMETypeList.Add(".dl", "video/x-dl");
            MIMETypeList.Add(".doc", "application/msword")
            MIMETypeList.Add(".dot", "application/msword")
            MIMETypeList.Add(".dp", "application/commonground")
            MIMETypeList.Add(".drw", "application/drafting")
            MIMETypeList.Add(".dump", "application/octet-stream")
            MIMETypeList.Add(".dv", "video/x-dv")
            MIMETypeList.Add(".dvi", "application/x-dvi")
            MIMETypeList.Add(".dwf", "drawing/x-dwf (old)")
            'MIMETypeList.Add(".dwf", "model/vnd.dwf");
            'MIMETypeList.Add(".dwg", "application/acad");
            MIMETypeList.Add(".dwg", "image/vnd.dwg")
            'MIMETypeList.Add(".dwg", "image/x-dwg");
            'MIMETypeList.Add(".dxf", "application/dxf");
            'MIMETypeList.Add(".dxf", "image/vnd.dwg");
            MIMETypeList.Add(".dxf", "image/x-dwg")
            MIMETypeList.Add(".dxr", "application/x-director")
            MIMETypeList.Add(".el", "text/x-script.elisp")
            'MIMETypeList.Add(".elc", "application/x-bytecode.elisp (compiled elisp)");
            MIMETypeList.Add(".elc", "application/x-elc")
            MIMETypeList.Add(".env", "application/x-envoy")
            MIMETypeList.Add(".eps", "application/postscript")
            MIMETypeList.Add(".es", "application/x-esrehber")
            MIMETypeList.Add(".etx", "text/x-setext")
            MIMETypeList.Add(".evy", "application/envoy")
            'MIMETypeList.Add(".evy", "application/x-envoy");
            MIMETypeList.Add(".exe", "application/octet-stream")
            MIMETypeList.Add(".f", "text/plain")
            'MIMETypeList.Add(".f", "text/x-fortran");
            MIMETypeList.Add(".f77", "text/x-fortran")
            MIMETypeList.Add(".f90", "text/plain")
            'MIMETypeList.Add(".f90", "text/x-fortran");
            MIMETypeList.Add(".fdf", "application/vnd.fdf")
            'MIMETypeList.Add(".fif", "application/fractals");
            MIMETypeList.Add(".fif", "image/fif")
            MIMETypeList.Add(".fli", "video/fli")
            'MIMETypeList.Add(".fli", "video/x-fli");
            MIMETypeList.Add(".flo", "image/florian")
            MIMETypeList.Add(".flx", "text/vnd.fmi.flexstor")
            MIMETypeList.Add(".fmf", "video/x-atomic3d-feature")
            MIMETypeList.Add(".for", "text/plain")
            'MIMETypeList.Add(".for", "text/x-fortran");
            MIMETypeList.Add(".fpx", "image/vnd.fpx")
            'MIMETypeList.Add(".fpx", "image/vnd.net-fpx");
            MIMETypeList.Add(".frl", "application/freeloader")
            MIMETypeList.Add(".funk", "audio/make")
            MIMETypeList.Add(".g", "text/plain")
            MIMETypeList.Add(".g3", "image/g3fax")
            MIMETypeList.Add(".gif", "image/gif")
            MIMETypeList.Add(".gl", "video/gl")
            'MIMETypeList.Add(".gl", "video/x-gl");
            MIMETypeList.Add(".gsd", "audio/x-gsm")
            MIMETypeList.Add(".gsm", "audio/x-gsm")
            MIMETypeList.Add(".gsp", "application/x-gsp")
            MIMETypeList.Add(".gss", "application/x-gss")
            MIMETypeList.Add(".gtar", "application/x-gtar")
            'MIMETypeList.Add(".gz", "application/x-compressed");
            MIMETypeList.Add(".gz", "application/x-gzip")
            'MIMETypeList.Add(".gzip", "application/x-gzip");
            MIMETypeList.Add(".gzip", "multipart/x-gzip")
            MIMETypeList.Add(".h", "text/plain")
            'MIMETypeList.Add(".h", "text/x-h");
            MIMETypeList.Add(".hdf", "application/x-hdf")
            MIMETypeList.Add(".help", "application/x-helpfile")
            MIMETypeList.Add(".hgl", "application/vnd.hp-hpgl")
            MIMETypeList.Add(".hh", "text/plain")
            'MIMETypeList.Add(".hh", "text/x-h");
            MIMETypeList.Add(".hlb", "text/x-script")
            MIMETypeList.Add(".hlp", "application/hlp")
            'MIMETypeList.Add(".hlp", "application/x-helpfile");
            'MIMETypeList.Add(".hlp", "application/x-winhelp");
            MIMETypeList.Add(".hpg", "application/vnd.hp-hpgl")
            MIMETypeList.Add(".hpgl", "application/vnd.hp-hpgl")
            MIMETypeList.Add(".hqx", "application/binhex")
            'MIMETypeList.Add(".hqx", "application/binhex4");
            'MIMETypeList.Add(".hqx", "application/mac-binhex");
            'MIMETypeList.Add(".hqx", "application/mac-binhex40");
            'MIMETypeList.Add(".hqx", "application/x-binhex40");
            'MIMETypeList.Add(".hqx", "application/x-mac-binhex40");
            MIMETypeList.Add(".hta", "application/hta")
            MIMETypeList.Add(".htc", "text/x-component")
            MIMETypeList.Add(".htm", "text/html")
            MIMETypeList.Add(".html", "text/html")
            MIMETypeList.Add(".htmls", "text/html")
            MIMETypeList.Add(".htt", "text/webviewhtml")
            MIMETypeList.Add(".htx", "text/html")
            MIMETypeList.Add(".ice", "x-conference/x-cooltalk")
            MIMETypeList.Add(".ico", "image/x-icon")

            MIMETypeList.Add(".ics", "text/calendar")
            'MIMETypeList.Add(".ics", "text/x-vCalendar")

            MIMETypeList.Add(".idc", "text/plain")
            MIMETypeList.Add(".ief", "image/ief")
            MIMETypeList.Add(".iefs", "image/ief")
            MIMETypeList.Add(".iges", "application/iges")
            'MIMETypeList.Add(".iges", "model/iges");
            MIMETypeList.Add(".igs", "application/iges")
            'MIMETypeList.Add(".igs", "model/iges");
            MIMETypeList.Add(".ima", "application/x-ima")
            MIMETypeList.Add(".imap", "application/x-httpd-imap")
            MIMETypeList.Add(".inf", "application/inf")
            MIMETypeList.Add(".ins", "application/x-internett-signup")
            MIMETypeList.Add(".ip", "application/x-ip2")
            MIMETypeList.Add(".isu", "video/x-isvideo")
            MIMETypeList.Add(".it", "audio/it")
            MIMETypeList.Add(".iv", "application/x-inventor")
            MIMETypeList.Add(".ivr", "i-world/i-vrml")
            MIMETypeList.Add(".ivy", "application/x-livescreen")
            MIMETypeList.Add(".jam", "audio/x-jam")
            MIMETypeList.Add(".jav", "text/plain")
            'MIMETypeList.Add(".jav", "text/x-java-source");
            MIMETypeList.Add(".java", "text/plain")
            'MIMETypeList.Add(".java", "text/x-java-source");
            MIMETypeList.Add(".jcm", "application/x-java-commerce")
            MIMETypeList.Add(".jfif", "image/jpeg")
            'MIMETypeList.Add(".jfif", "image/pjpeg");
            MIMETypeList.Add(".jfif-tbnl", "image/jpeg")
            MIMETypeList.Add(".jpe", "image/jpeg")
            'MIMETypeList.Add(".jpe", "image/pjpeg");
            MIMETypeList.Add(".jpeg", "image/jpeg")
            'MIMETypeList.Add(".jpeg", "image/pjpeg");
            MIMETypeList.Add(".jpg", "image/jpeg")
            'MIMETypeList.Add(".jpg", "image/pjpeg");
            MIMETypeList.Add(".jps", "image/x-jps")
            'MIMETypeList.Add(".js", "application/x-javascript");
            'MIMETypeList.Add(".js", "application/javascript");
            'MIMETypeList.Add(".js", "application/ecmascript");
            MIMETypeList.Add(".js", "text/javascript")
            'MIMETypeList.Add(".js", "text/ecmascript");
            MIMETypeList.Add(".jut", "image/jutvision")
            MIMETypeList.Add(".kar", "audio/midi")
            'MIMETypeList.Add(".kar", "music/x-karaoke");
            'MIMETypeList.Add(".ksh", "application/x-ksh");
            MIMETypeList.Add(".ksh", "text/x-script.ksh")
            MIMETypeList.Add(".la", "audio/nspaudio")
            'MIMETypeList.Add(".la", "audio/x-nspaudio");
            MIMETypeList.Add(".lam", "audio/x-liveaudio")
            MIMETypeList.Add(".latex", "application/x-latex")
            MIMETypeList.Add(".lha", "application/lha")
            'MIMETypeList.Add(".lha", "application/octet-stream");
            'MIMETypeList.Add(".lha", "application/x-lha");
            MIMETypeList.Add(".lhx", "application/octet-stream")
            MIMETypeList.Add(".list", "text/plain")
            MIMETypeList.Add(".lma", "audio/nspaudio")
            'MIMETypeList.Add(".lma", "audio/x-nspaudio");
            MIMETypeList.Add(".log", "text/plain")
            'MIMETypeList.Add(".lsp", "application/x-lisp");
            MIMETypeList.Add(".lsp", "text/x-script.lisp")
            MIMETypeList.Add(".lst", "text/plain")
            MIMETypeList.Add(".lsx", "text/x-la-asf")
            MIMETypeList.Add(".ltx", "application/x-latex")
            'MIMETypeList.Add(".lzh", "application/octet-stream");
            MIMETypeList.Add(".lzh", "application/x-lzh")
            MIMETypeList.Add(".lzx", "application/lzx")
            'MIMETypeList.Add(".lzx", "application/octet-stream");
            'MIMETypeList.Add(".lzx", "application/x-lzx");
            MIMETypeList.Add(".m", "text/plain")
            'MIMETypeList.Add(".m", "text/x-m");
            MIMETypeList.Add(".m1v", "video/mpeg")
            MIMETypeList.Add(".m2a", "audio/mpeg")
            MIMETypeList.Add(".m2v", "video/mpeg")
            MIMETypeList.Add(".m3u", "audio/x-mpequrl")
            MIMETypeList.Add(".man", "application/x-troff-man")
            'MIMETypeList.Add(".map", "application/x-navimap");
            MIMETypeList.Add(".mar", "text/plain")
            MIMETypeList.Add(".mbd", "application/mbedlet")
            MIMETypeList.Add(".mc$", "application/x-magic-cap-package-1.0")
            MIMETypeList.Add(".mcd", "application/mcad")
            'MIMETypeList.Add(".mcd", "application/x-mathcad");
            MIMETypeList.Add(".mcf", "image/vasa")
            'MIMETypeList.Add(".mcf", "text/mcf");
            MIMETypeList.Add(".mcp", "application/netmc")
            MIMETypeList.Add(".me", "application/x-troff-me")
            MIMETypeList.Add(".mht", "message/rfc822")
            MIMETypeList.Add(".mhtml", "message/rfc822")
            'MIMETypeList.Add(".mid", "application/x-midi");
            MIMETypeList.Add(".mid", "audio/midi")
            'MIMETypeList.Add(".mid", "audio/x-mid");
            'MIMETypeList.Add(".mid", "audio/x-midi");
            'MIMETypeList.Add(".mid", "music/crescendo");
            'MIMETypeList.Add(".mid", "x-music/x-midi");
            'MIMETypeList.Add(".midi", "application/x-midi");
            MIMETypeList.Add(".midi", "audio/midi")
            'MIMETypeList.Add(".midi", "audio/x-mid");
            'MIMETypeList.Add(".midi", "audio/x-midi");
            'MIMETypeList.Add(".midi", "music/crescendo");
            'MIMETypeList.Add(".midi", "x-music/x-midi");
            MIMETypeList.Add(".mif", "application/x-frame")
            'MIMETypeList.Add(".mif", "application/x-mif");
            MIMETypeList.Add(".mime", "message/rfc822")
            'MIMETypeList.Add(".mime", "www/mime");
            MIMETypeList.Add(".mjf", "audio/x-vnd.audioexplosion.mjuicemediafile")
            MIMETypeList.Add(".mjpg", "video/x-motion-jpeg")
            MIMETypeList.Add(".mm", "application/base64")
            'MIMETypeList.Add(".mm", "application/x-meme");
            MIMETypeList.Add(".mme", "application/base64")
            MIMETypeList.Add(".mod", "audio/mod")
            'MIMETypeList.Add(".mod", "audio/x-mod");
            MIMETypeList.Add(".moov", "video/quicktime")
            MIMETypeList.Add(".mov", "video/quicktime")
            MIMETypeList.Add(".movie", "video/x-sgi-movie")
            MIMETypeList.Add(".mp2", "audio/mpeg")
            'MIMETypeList.Add(".mp2", "audio/x-mpeg");
            'MIMETypeList.Add(".mp2", "video/mpeg");
            'MIMETypeList.Add(".mp2", "video/x-mpeg");
            'MIMETypeList.Add(".mp2", "video/x-mpeq2a");
            'MIMETypeList.Add(".mp3", "audio/mpeg3");
            'MIMETypeList.Add(".mp3", "audio/x-mpeg-3");
            MIMETypeList.Add(".mp3", "video/mpeg")
            'MIMETypeList.Add(".mp3", "video/x-mpeg");
            MIMETypeList.Add(".mpa", "audio/mpeg")
            'MIMETypeList.Add(".mpa", "video/mpeg");
            MIMETypeList.Add(".mpc", "application/x-project")
            MIMETypeList.Add(".mpe", "video/mpeg")
            MIMETypeList.Add(".mpeg", "video/mpeg")
            'MIMETypeList.Add(".mpg", "audio/mpeg");
            MIMETypeList.Add(".mpg", "video/mpeg")
            MIMETypeList.Add(".mpga", "audio/mpeg")
            MIMETypeList.Add(".mpp", "application/vnd.ms-project")
            MIMETypeList.Add(".mpt", "application/x-project")
            MIMETypeList.Add(".mpv", "application/x-project")
            MIMETypeList.Add(".mpx", "application/x-project")
            MIMETypeList.Add(".mrc", "application/marc")
            MIMETypeList.Add(".ms", "application/x-troff-ms")
            MIMETypeList.Add(".mv", "video/x-sgi-movie")
            MIMETypeList.Add(".my", "audio/make")
            MIMETypeList.Add(".mzz", "application/x-vnd.audioexplosion.mzz")
            MIMETypeList.Add(".nap", "image/naplps")
            MIMETypeList.Add(".naplps", "image/naplps")
            MIMETypeList.Add(".nc", "application/x-netcdf")
            MIMETypeList.Add(".ncm", "application/vnd.nokia.configuration-message")
            MIMETypeList.Add(".nif", "image/x-niff")
            MIMETypeList.Add(".niff", "image/x-niff")
            MIMETypeList.Add(".nix", "application/x-mix-transfer")
            MIMETypeList.Add(".nsc", "application/x-conference")
            MIMETypeList.Add(".nvd", "application/x-navidoc")
            MIMETypeList.Add(".o", "application/octet-stream")
            MIMETypeList.Add(".oda", "application/oda")
            MIMETypeList.Add(".omc", "application/x-omc")
            MIMETypeList.Add(".omcd", "application/x-omcdatamaker")
            MIMETypeList.Add(".omcr", "application/x-omcregerator")
            MIMETypeList.Add(".p", "text/x-pascal")
            MIMETypeList.Add(".p10", "application/pkcs10")
            'MIMETypeList.Add(".p10", "application/x-pkcs10");
            MIMETypeList.Add(".p12", "application/pkcs-12")
            'MIMETypeList.Add(".p12", "application/x-pkcs12");
            MIMETypeList.Add(".p7a", "application/x-pkcs7-signature")
            MIMETypeList.Add(".p7c", "application/pkcs7-mime")
            'MIMETypeList.Add(".p7c", "application/x-pkcs7-mime");
            MIMETypeList.Add(".p7m", "application/pkcs7-mime")
            'MIMETypeList.Add(".p7m", "application/x-pkcs7-mime");
            MIMETypeList.Add(".p7r", "application/x-pkcs7-certreqresp")
            MIMETypeList.Add(".p7s", "application/pkcs7-signature")
            MIMETypeList.Add(".part", "application/pro_eng")
            MIMETypeList.Add(".pas", "text/pascal")
            MIMETypeList.Add(".pbm", "image/x-portable-bitmap")
            'MIMETypeList.Add(".pcl", "application/vnd.hp-pcl");
            MIMETypeList.Add(".pcl", "application/x-pcl")
            MIMETypeList.Add(".pct", "image/x-pict")
            MIMETypeList.Add(".pcx", "image/x-pcx")
            MIMETypeList.Add(".pdb", "chemical/x-pdb")
            MIMETypeList.Add(".pdf", "application/pdf")
            MIMETypeList.Add(".pfunk", "audio/make")
            'MIMETypeList.Add(".pfunk", "audio/make.my.funk");
            MIMETypeList.Add(".pgm", "image/x-portable-graymap")
            'MIMETypeList.Add(".pgm", "image/x-portable-greymap");
            MIMETypeList.Add(".pic", "image/pict")
            MIMETypeList.Add(".pict", "image/pict")
            MIMETypeList.Add(".pkg", "application/x-newton-compatible-pkg")
            MIMETypeList.Add(".pko", "application/vnd.ms-pki.pko")
            MIMETypeList.Add(".pl", "text/plain")
            'MIMETypeList.Add(".pl", "text/x-script.perl");
            MIMETypeList.Add(".plx", "application/x-pixclscript")
            MIMETypeList.Add(".pm", "image/x-xpixmap")
            'MIMETypeList.Add(".pm", "text/x-script.perl-module");
            MIMETypeList.Add(".pm4", "application/x-pagemaker")
            MIMETypeList.Add(".pm5", "application/x-pagemaker")
            MIMETypeList.Add(".png", "image/png")
            'MIMETypeList.Add(".pnm", "application/x-portable-anymap");
            MIMETypeList.Add(".pnm", "image/x-portable-anymap")
            MIMETypeList.Add(".pot", "application/mspowerpoint")
            'MIMETypeList.Add(".pot", "application/vnd.ms-powerpoint");
            MIMETypeList.Add(".pov", "model/x-pov")
            MIMETypeList.Add(".ppa", "application/vnd.ms-powerpoint")
            MIMETypeList.Add(".ppm", "image/x-portable-pixmap")
            MIMETypeList.Add(".pps", "application/mspowerpoint")
            'MIMETypeList.Add(".pps", "application/vnd.ms-powerpoint");
            'MIMETypeList.Add(".ppt", "application/mspowerpoint");
            MIMETypeList.Add(".ppt", "application/powerpoint")
            'MIMETypeList.Add(".ppt", "application/vnd.ms-powerpoint");
            'MIMETypeList.Add(".ppt", "application/x-mspowerpoint");
            MIMETypeList.Add(".ppz", "application/mspowerpoint")
            MIMETypeList.Add(".pre", "application/x-freelance")
            MIMETypeList.Add(".prt", "application/pro_eng")
            MIMETypeList.Add(".ps", "application/postscript")
            MIMETypeList.Add(".psd", "application/octet-stream")
            MIMETypeList.Add(".pvu", "paleovu/x-pv")
            MIMETypeList.Add(".pwz", "application/vnd.ms-powerpoint")
            MIMETypeList.Add(".py", "text/x-script.phyton")
            MIMETypeList.Add(".pyc", "applicaiton/x-bytecode.python")
            MIMETypeList.Add(".qcp", "audio/vnd.qcelp")
            MIMETypeList.Add(".qd3", "x-world/x-3dmf")
            MIMETypeList.Add(".qd3d", "x-world/x-3dmf")
            MIMETypeList.Add(".qif", "image/x-quicktime")
            MIMETypeList.Add(".qt", "video/quicktime")
            MIMETypeList.Add(".qtc", "video/x-qtc")
            MIMETypeList.Add(".qti", "image/x-quicktime")
            MIMETypeList.Add(".qtif", "image/x-quicktime")
            'MIMETypeList.Add(".ra", "audio/x-pn-realaudio");
            'MIMETypeList.Add(".ra", "audio/x-pn-realaudio-plugin");
            MIMETypeList.Add(".ra", "audio/x-realaudio")
            MIMETypeList.Add(".ram", "audio/x-pn-realaudio")
            'MIMETypeList.Add(".ras", "application/x-cmu-raster");
            MIMETypeList.Add(".ras", "image/cmu-raster")
            'MIMETypeList.Add(".ras", "image/x-cmu-raster");
            MIMETypeList.Add(".rast", "image/cmu-raster")
            MIMETypeList.Add(".rexx", "text/x-script.rexx")
            MIMETypeList.Add(".rf", "image/vnd.rn-realflash")
            MIMETypeList.Add(".rgb", "image/x-rgb")
            'MIMETypeList.Add(".rm", "application/vnd.rn-realmedia");
            MIMETypeList.Add(".rm", "audio/x-pn-realaudio")
            MIMETypeList.Add(".rmi", "audio/mid")
            MIMETypeList.Add(".rmm", "audio/x-pn-realaudio")
            MIMETypeList.Add(".rmp", "audio/x-pn-realaudio")
            'MIMETypeList.Add(".rmp", "audio/x-pn-realaudio-plugin");
            MIMETypeList.Add(".rng", "application/ringing-tones")
            'MIMETypeList.Add(".rng", "application/vnd.nokia.ringing-tone");
            MIMETypeList.Add(".rnx", "application/vnd.rn-realplayer")
            MIMETypeList.Add(".roff", "application/x-troff")
            MIMETypeList.Add(".rp", "image/vnd.rn-realpix")
            MIMETypeList.Add(".rpm", "audio/x-pn-realaudio-plugin")
            MIMETypeList.Add(".rt", "text/richtext")
            'MIMETypeList.Add(".rt", "text/vnd.rn-realtext");
            'MIMETypeList.Add(".rtf", "application/rtf");
            'MIMETypeList.Add(".rtf", "application/x-rtf");
            MIMETypeList.Add(".rtf", "text/richtext")
            'MIMETypeList.Add(".rtx", "application/rtf");
            MIMETypeList.Add(".rtx", "text/richtext")
            MIMETypeList.Add(".rv", "video/vnd.rn-realvideo")
            MIMETypeList.Add(".s", "text/x-asm")
            MIMETypeList.Add(".s3m", "audio/s3m")
            MIMETypeList.Add(".saveme", "application/octet-stream")
            MIMETypeList.Add(".sbk", "application/x-tbook")
            'MIMETypeList.Add(".scm", "application/x-lotusscreencam");
            MIMETypeList.Add(".scm", "text/x-script.guile")
            'MIMETypeList.Add(".scm", "text/x-script.scheme");
            'MIMETypeList.Add(".scm", "video/x-scm");
            MIMETypeList.Add(".sdml", "text/plain")
            MIMETypeList.Add(".sdp", "application/sdp")
            'MIMETypeList.Add(".sdp", "application/x-sdp");
            MIMETypeList.Add(".sdr", "application/sounder")
            MIMETypeList.Add(".sea", "application/sea")
            'MIMETypeList.Add(".sea", "application/x-sea");
            MIMETypeList.Add(".set", "application/set")
            MIMETypeList.Add(".sgm", "text/sgml")
            'MIMETypeList.Add(".sgm", "text/x-sgml");
            MIMETypeList.Add(".sgml", "text/sgml")
            'MIMETypeList.Add(".sgml", "text/x-sgml");
            'MIMETypeList.Add(".sh", "application/x-bsh");
            'MIMETypeList.Add(".sh", "application/x-sh");
            'MIMETypeList.Add(".sh", "application/x-shar");
            MIMETypeList.Add(".sh", "text/x-script.sh")
            'MIMETypeList.Add(".shar", "application/x-bsh");
            MIMETypeList.Add(".shar", "application/x-shar")
            MIMETypeList.Add(".shtml", "text/html")
            'MIMETypeList.Add(".shtml", "text/x-server-parsed-html");
            MIMETypeList.Add(".sid", "audio/x-psid")

            MIMETypeList.Add(".sis", "application/vnd.symbian.install")


            MIMETypeList.Add(".sit", "application/x-sit")
            'MIMETypeList.Add(".sit", "application/x-stuffit");
            MIMETypeList.Add(".skd", "application/x-koan")
            MIMETypeList.Add(".skm", "application/x-koan")
            MIMETypeList.Add(".skp", "application/x-koan")
            MIMETypeList.Add(".skt", "application/x-koan")
            MIMETypeList.Add(".sl", "application/x-seelogo")
            MIMETypeList.Add(".smi", "application/smil")
            MIMETypeList.Add(".smil", "application/smil")
            MIMETypeList.Add(".snd", "audio/basic")
            'MIMETypeList.Add(".snd", "audio/x-adpcm");
            MIMETypeList.Add(".sol", "application/solids")
            'MIMETypeList.Add(".spc", "application/x-pkcs7-certificates");
            MIMETypeList.Add(".spc", "text/x-speech")
            MIMETypeList.Add(".spl", "application/futuresplash")
            MIMETypeList.Add(".spr", "application/x-sprite")
            MIMETypeList.Add(".sprite", "application/x-sprite")
            MIMETypeList.Add(".src", "application/x-wais-source")
            MIMETypeList.Add(".ssi", "text/x-server-parsed-html")
            MIMETypeList.Add(".ssm", "application/streamingmedia")
            MIMETypeList.Add(".sst", "application/vnd.ms-pki.certstore")
            MIMETypeList.Add(".step", "application/step")
            MIMETypeList.Add(".stl", "application/sla")
            'MIMETypeList.Add(".stl", "application/vnd.ms-pki.stl");
            'MIMETypeList.Add(".stl", "application/x-navistyle");
            MIMETypeList.Add(".stp", "application/step")
            MIMETypeList.Add(".sv4cpio", "application/x-sv4cpio")
            MIMETypeList.Add(".sv4crc", "application/x-sv4crc")
            MIMETypeList.Add(".svf", "image/vnd.dwg")
            'MIMETypeList.Add(".svf", "image/x-dwg");
            MIMETypeList.Add(".svr", "application/x-world")
            'MIMETypeList.Add(".svr", "x-world/x-svr");
            MIMETypeList.Add(".swf", "application/x-shockwave-flash")
            MIMETypeList.Add(".t", "application/x-troff")
            MIMETypeList.Add(".talk", "text/x-speech")
            MIMETypeList.Add(".tar", "application/x-tar")
            MIMETypeList.Add(".tbk", "application/toolbook")
            'MIMETypeList.Add(".tbk", "application/x-tbook");
            'MIMETypeList.Add(".tcl", "application/x-tcl");
            MIMETypeList.Add(".tcl", "text/x-script.tcl")
            MIMETypeList.Add(".tcsh", "text/x-script.tcsh")
            MIMETypeList.Add(".tex", "application/x-tex")
            MIMETypeList.Add(".texi", "application/x-texinfo")
            MIMETypeList.Add(".texinfo", "application/x-texinfo")
            'MIMETypeList.Add(".text", "application/plain");
            MIMETypeList.Add(".text", "text/plain")
            MIMETypeList.Add(".tgz", "application/gnutar")
            'MIMETypeList.Add(".tgz", "application/x-compressed");
            MIMETypeList.Add(".tif", "image/tiff")
            'MIMETypeList.Add(".tif", "image/x-tiff");
            MIMETypeList.Add(".tiff", "image/tiff")
            'MIMETypeList.Add(".tiff", "image/x-tiff");
            MIMETypeList.Add(".tr", "application/x-troff")
            MIMETypeList.Add(".tsi", "audio/tsp-audio")
            'MIMETypeList.Add(".tsp", "application/dsptype");
            MIMETypeList.Add(".tsp", "audio/tsplayer")
            MIMETypeList.Add(".tsv", "text/tab-separated-values")
            MIMETypeList.Add(".turbot", "image/florian")
            MIMETypeList.Add(".txt", "text/plain")
            MIMETypeList.Add(".uil", "text/x-uil")
            MIMETypeList.Add(".uni", "text/uri-list")
            MIMETypeList.Add(".unis", "text/uri-list")
            MIMETypeList.Add(".unv", "application/i-deas")
            MIMETypeList.Add(".uri", "text/uri-list")
            MIMETypeList.Add(".uris", "text/uri-list")
            MIMETypeList.Add(".ustar", "application/x-ustar")
            'MIMETypeList.Add(".ustar", "multipart/x-ustar");
            'MIMETypeList.Add(".uu", "application/octet-stream");
            MIMETypeList.Add(".uu", "text/x-uuencode")
            MIMETypeList.Add(".uue", "text/x-uuencode")
            MIMETypeList.Add(".vcd", "application/x-cdlink")
            MIMETypeList.Add(".vcf", "text/x-vcard")
            MIMETypeList.Add(".vcs", "text/x-vcalendar")
            MIMETypeList.Add(".vda", "application/vda")
            MIMETypeList.Add(".vdo", "video/vdo")
            MIMETypeList.Add(".vew", "application/groupwise")
            MIMETypeList.Add(".viv", "video/vivo")
            'MIMETypeList.Add(".viv", "video/vnd.vivo");
            MIMETypeList.Add(".vivo", "video/vivo")
            'MIMETypeList.Add(".vivo", "video/vnd.vivo");
            MIMETypeList.Add(".vmd", "application/vocaltec-media-desc")
            MIMETypeList.Add(".vmf", "application/vocaltec-media-file")
            MIMETypeList.Add(".voc", "audio/voc")
            'MIMETypeList.Add(".voc", "audio/x-voc");
            MIMETypeList.Add(".vos", "video/vosaic")
            MIMETypeList.Add(".vox", "audio/voxware")
            MIMETypeList.Add(".vqe", "audio/x-twinvq-plugin")
            MIMETypeList.Add(".vqf", "audio/x-twinvq")
            MIMETypeList.Add(".vql", "audio/x-twinvq-plugin")
            'MIMETypeList.Add(".vrml", "application/x-vrml");
            MIMETypeList.Add(".vrml", "model/vrml")
            'MIMETypeList.Add(".vrml", "x-world/x-vrml");
            MIMETypeList.Add(".vrt", "x-world/x-vrt")
            MIMETypeList.Add(".vsd", "application/x-visio")
            MIMETypeList.Add(".vst", "application/x-visio")
            MIMETypeList.Add(".vsw", "application/x-visio")
            MIMETypeList.Add(".w60", "application/wordperfect6.0")
            MIMETypeList.Add(".w61", "application/wordperfect6.1")
            MIMETypeList.Add(".w6w", "application/msword")
            MIMETypeList.Add(".wav", "audio/wav")
            'MIMETypeList.Add(".wav", "audio/x-wav");
            MIMETypeList.Add(".wb1", "application/x-qpro")
            MIMETypeList.Add(".wbmp", "image/vnd.wap.wbmp")
            MIMETypeList.Add(".web", "application/vnd.xara")
            MIMETypeList.Add(".wiz", "application/msword")
            MIMETypeList.Add(".wk1", "application/x-123")
            MIMETypeList.Add(".wmf", "windows/metafile")
            MIMETypeList.Add(".wml", "text/vnd.wap.wml")
            MIMETypeList.Add(".wmlc", "application/vnd.wap.wmlc")
            MIMETypeList.Add(".wmls", "text/vnd.wap.wmlscript")
            MIMETypeList.Add(".wmlsc", "application/vnd.wap.wmlscriptc")
            MIMETypeList.Add(".word", "application/msword")
            MIMETypeList.Add(".wp", "application/wordperfect")
            MIMETypeList.Add(".wp5", "application/wordperfect")
            'MIMETypeList.Add(".wp5", "application/wordperfect6.0");
            MIMETypeList.Add(".wp6", "application/wordperfect")
            MIMETypeList.Add(".wpd", "application/wordperfect")
            'MIMETypeList.Add(".wpd", "application/x-wpwin");
            MIMETypeList.Add(".wq1", "application/x-lotus")
            MIMETypeList.Add(".wri", "application/mswrite")
            'MIMETypeList.Add(".wri", "application/x-wri");
            'MIMETypeList.Add(".wrl", "application/x-world");
            MIMETypeList.Add(".wrl", "model/vrml")
            'MIMETypeList.Add(".wrl", "x-world/x-vrml");
            MIMETypeList.Add(".wrz", "model/vrml")
            'MIMETypeList.Add(".wrz", "x-world/x-vrml");
            MIMETypeList.Add(".wsc", "text/scriplet")
            MIMETypeList.Add(".wsrc", "application/x-wais-source")
            MIMETypeList.Add(".wtk", "application/x-wintalk")
            'MIMETypeList.Add(".xbm", "image/x-xbitmap");
            'MIMETypeList.Add(".xbm", "image/x-xbm");
            MIMETypeList.Add(".xbm", "image/xbm")
            MIMETypeList.Add(".xdr", "video/x-amt-demorun")
            MIMETypeList.Add(".xgz", "xgl/drawing")
            MIMETypeList.Add(".xif", "image/vnd.xiff")
            MIMETypeList.Add(".xl", "application/excel")
            MIMETypeList.Add(".xla", "application/excel")
            'MIMETypeList.Add(".xla", "application/x-excel");
            'MIMETypeList.Add(".xla", "application/x-msexcel");
            MIMETypeList.Add(".xlb", "application/excel")
            'MIMETypeList.Add(".xlb", "application/vnd.ms-excel");
            'MIMETypeList.Add(".xlb", "application/x-excel");
            MIMETypeList.Add(".xlc", "application/excel")
            'MIMETypeList.Add(".xlc", "application/vnd.ms-excel");
            'MIMETypeList.Add(".xlc", "application/x-excel");
            MIMETypeList.Add(".xld", "application/excel")
            'MIMETypeList.Add(".xld", "application/x-excel");
            MIMETypeList.Add(".xlk", "application/excel")
            'MIMETypeList.Add(".xlk", "application/x-excel");
            MIMETypeList.Add(".xll", "application/excel")
            'MIMETypeList.Add(".xll", "application/vnd.ms-excel");
            'MIMETypeList.Add(".xll", "application/x-excel");
            MIMETypeList.Add(".xlm", "application/excel")
            'MIMETypeList.Add(".xlm", "application/vnd.ms-excel");
            'MIMETypeList.Add(".xlm", "application/x-excel");
            MIMETypeList.Add(".xls", "application/excel")
            'MIMETypeList.Add(".xls", "application/vnd.ms-excel");
            'MIMETypeList.Add(".xls", "application/x-excel");
            'MIMETypeList.Add(".xls", "application/x-msexcel");
            MIMETypeList.Add(".xlt", "application/excel")
            'MIMETypeList.Add(".xlt", "application/x-excel");
            MIMETypeList.Add(".xlv", "application/excel")
            'MIMETypeList.Add(".xlv", "application/x-excel");
            MIMETypeList.Add(".xlw", "application/excel")
            'MIMETypeList.Add(".xlw", "application/vnd.ms-excel");
            'MIMETypeList.Add(".xlw", "application/x-excel");
            'MIMETypeList.Add(".xlw", "application/x-msexcel");
            MIMETypeList.Add(".xm", "audio/xm")
            'MIMETypeList.Add(".xml", "application/xml");
            MIMETypeList.Add(".xml", "text/xml")
            MIMETypeList.Add(".xmz", "xgl/movie")
            MIMETypeList.Add(".xpix", "application/x-vnd.ls-xpix")
            'MIMETypeList.Add(".xpm", "image/x-xpixmap");
            MIMETypeList.Add(".xpm", "image/xpm")
            MIMETypeList.Add(".x-png", "image/png")
            MIMETypeList.Add(".xsr", "video/x-amt-showrun")
            MIMETypeList.Add(".xwd", "image/x-xwd")
            'MIMETypeList.Add(".xwd", "image/x-xwindowdump");
            MIMETypeList.Add(".xyz", "chemical/x-pdb")
            MIMETypeList.Add(".z", "application/x-compress")
            'MIMETypeList.Add(".z", "application/x-compressed");
            'MIMETypeList.Add(".zip", "application/x-compressed");
            MIMETypeList.Add(".zip", "application/x-zip-compressed")
            'MIMETypeList.Add(".zip", "application/zip");
            'MIMETypeList.Add(".zip", "multipart/x-zip");
            MIMETypeList.Add(".zoo", "application/octet-stream")
            MIMETypeList.Add(".zsh", "text/x-script.zsh")
        Catch ex As Exception
            MessageBox.Show(ex.Message, Application.ProductName, MessageBoxButtons.OK, MessageBoxIcon.[Error])
        End Try
    End Sub
End Class