//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace SmsTest.com.webservicex.www {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SendSMSWorldSoap", Namespace="http://www.webserviceX.NET")]
    public class SendSMSWorld : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public SendSMSWorld() {
            this.Url = "http://www.webservicex.com/sendsmsworld.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webserviceX.NET/sendSMS", RequestNamespace="http://www.webserviceX.NET", ResponseNamespace="http://www.webserviceX.NET", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sendSMS(string FromEmailAddress, string CountryCode, string MobileNumber, string Message) {
            object[] results = this.Invoke("sendSMS", new object[] {
                        FromEmailAddress,
                        CountryCode,
                        MobileNumber,
                        Message});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsendSMS(string FromEmailAddress, string CountryCode, string MobileNumber, string Message, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sendSMS", new object[] {
                        FromEmailAddress,
                        CountryCode,
                        MobileNumber,
                        Message}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsendSMS(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
